'use strict';
/* Автоматически собранный список ресурсов (tools/gen_manifest.py). Всего: 23.6 МБ, файлов: 175 */
const MANIFEST = [
  {"p": "assets/fonts/Neucha-cyrillic.woff2", "s": 19308, "t": "font", "family": "Neucha", "range": "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", "weight": "normal"},
  {"p": "assets/fonts/Neucha-latin.woff2", "s": 25376, "t": "font", "family": "Neucha", "range": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", "weight": "normal"},
  {"p": "assets/fonts/Rubik-cyrillic.woff2", "s": 15112, "t": "font", "family": "Rubik", "range": "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", "weight": "300 900"},
  {"p": "assets/fonts/Rubik-latin.woff2", "s": 35348, "t": "font", "family": "Rubik", "range": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", "weight": "300 900"},
  {"p": "assets/ui/map.jpg", "s": 197539, "t": "icon"},
  {"p": "assets/ui/paper.jpg", "s": 27217, "t": "icon"},
  {"p": "assets/ui/wood.jpg", "s": 64124, "t": "icon"},
  {"p": "assets/ui/wood_dark.jpg", "s": 57491, "t": "icon"},
  {"p": "assets/items/bait_barley.png", "s": 8355, "t": "icon"},
  {"p": "assets/items/bait_bloodworm.png", "s": 11838, "t": "icon"},
  {"p": "assets/items/bait_boilie.png", "s": 9149, "t": "icon"},
  {"p": "assets/items/bait_bread.png", "s": 19588, "t": "icon"},
  {"p": "assets/items/bait_caddis.png", "s": 13056, "t": "icon"},
  {"p": "assets/items/bait_corn.png", "s": 12669, "t": "icon"},
  {"p": "assets/items/bait_crayfish.png", "s": 16047, "t": "icon"},
  {"p": "assets/items/bait_dough.png", "s": 10308, "t": "icon"},
  {"p": "assets/items/bait_frog.png", "s": 14835, "t": "icon"},
  {"p": "assets/items/bait_grasshopper.png", "s": 16213, "t": "icon"},
  {"p": "assets/items/bait_livebait.png", "s": 12714, "t": "icon"},
  {"p": "assets/items/bait_maggot.png", "s": 13071, "t": "icon"},
  {"p": "assets/items/bait_pea.png", "s": 11920, "t": "icon"},
  {"p": "assets/items/bait_redworm.png", "s": 16740, "t": "icon"},
  {"p": "assets/items/bait_shell.png", "s": 11844, "t": "icon"},
  {"p": "assets/items/bait_worm.png", "s": 17076, "t": "icon"},
  {"p": "assets/items/charm.png", "s": 12824, "t": "icon"},
  {"p": "assets/items/coin.png", "s": 13811, "t": "icon"},
  {"p": "assets/items/gb_bream.png", "s": 12825, "t": "icon"},
  {"p": "assets/items/gb_carp.png", "s": 12795, "t": "icon"},
  {"p": "assets/items/gb_night.png", "s": 11993, "t": "icon"},
  {"p": "assets/items/gb_river.png", "s": 12463, "t": "icon"},
  {"p": "assets/items/gb_roach.png", "s": 13593, "t": "icon"},
  {"p": "assets/items/gb_universal.png", "s": 13499, "t": "icon"},
  {"p": "assets/items/hook_1.png", "s": 6340, "t": "icon"},
  {"p": "assets/items/hook_12.png", "s": 4816, "t": "icon"},
  {"p": "assets/items/hook_16.png", "s": 3721, "t": "icon"},
  {"p": "assets/items/hook_4.png", "s": 5193, "t": "icon"},
  {"p": "assets/items/hook_8.png", "s": 5996, "t": "icon"},
  {"p": "assets/items/junk_boot.png", "s": 16605, "t": "icon"},
  {"p": "assets/items/junk_bottle.png", "s": 26056, "t": "icon"},
  {"p": "assets/items/junk_can.png", "s": 34056, "t": "icon"},
  {"p": "assets/items/junk_chest.png", "s": 20762, "t": "icon"},
  {"p": "assets/items/junk_snag.png", "s": 52712, "t": "icon"},
  {"p": "assets/items/keepnet_1.png", "s": 38972, "t": "icon"},
  {"p": "assets/items/keepnet_2.png", "s": 43261, "t": "icon"},
  {"p": "assets/items/keepnet_3.png", "s": 46193, "t": "icon"},
  {"p": "assets/items/line_1.png", "s": 31540, "t": "icon"},
  {"p": "assets/items/line_2.png", "s": 32375, "t": "icon"},
  {"p": "assets/items/line_3.png", "s": 29002, "t": "icon"},
  {"p": "assets/items/line_4.png", "s": 38886, "t": "icon"},
  {"p": "assets/items/line_5.png", "s": 42627, "t": "icon"},
  {"p": "assets/items/line_6.png", "s": 41731, "t": "icon"},
  {"p": "assets/items/lure_crank.png", "s": 19147, "t": "icon"},
  {"p": "assets/items/lure_fly.png", "s": 14055, "t": "icon"},
  {"p": "assets/items/lure_popper.png", "s": 11098, "t": "icon"},
  {"p": "assets/items/lure_spinner_l.png", "s": 12191, "t": "icon"},
  {"p": "assets/items/lure_spinner_s.png", "s": 12570, "t": "icon"},
  {"p": "assets/items/lure_spoon.png", "s": 8583, "t": "icon"},
  {"p": "assets/items/lure_spoon_silver.png", "s": 8776, "t": "icon"},
  {"p": "assets/items/lure_twister.png", "s": 10671, "t": "icon"},
  {"p": "assets/items/lure_vibro.png", "s": 10895, "t": "icon"},
  {"p": "assets/items/lure_vibro_big.png", "s": 10431, "t": "icon"},
  {"p": "assets/items/lure_wobbler.png", "s": 14182, "t": "icon"},
  {"p": "assets/items/net.png", "s": 26470, "t": "icon"},
  {"p": "assets/items/reel_1.png", "s": 14802, "t": "icon"},
  {"p": "assets/items/reel_2.png", "s": 15753, "t": "icon"},
  {"p": "assets/items/reel_3.png", "s": 17020, "t": "icon"},
  {"p": "assets/items/reel_4.png", "s": 16886, "t": "icon"},
  {"p": "assets/items/reel_5.png", "s": 17129, "t": "icon"},
  {"p": "assets/items/rod_feeder_1.png", "s": 15842, "t": "icon"},
  {"p": "assets/items/rod_feeder_2.png", "s": 16522, "t": "icon"},
  {"p": "assets/items/rod_feeder_3.png", "s": 17239, "t": "icon"},
  {"p": "assets/items/rod_feeder_4.png", "s": 16469, "t": "icon"},
  {"p": "assets/items/rod_float_1.png", "s": 18369, "t": "icon"},
  {"p": "assets/items/rod_float_2.png", "s": 19037, "t": "icon"},
  {"p": "assets/items/rod_float_3.png", "s": 19059, "t": "icon"},
  {"p": "assets/items/rod_float_4.png", "s": 18439, "t": "icon"},
  {"p": "assets/items/rod_spin_1.png", "s": 17828, "t": "icon"},
  {"p": "assets/items/rod_spin_2.png", "s": 19099, "t": "icon"},
  {"p": "assets/items/rod_spin_3.png", "s": 18710, "t": "icon"},
  {"p": "assets/items/rod_spin_4.png", "s": 18967, "t": "icon"},
  {"p": "assets/items/sonar.png", "s": 6986, "t": "icon"},
  {"p": "assets/items/tacklebox.png", "s": 7910, "t": "icon"},
  {"p": "assets/items/thermos.png", "s": 4944, "t": "icon"},
  {"p": "assets/items/xp.png", "s": 18094, "t": "icon"},
  {"p": "assets/fish/amur.png", "s": 125132, "t": "fish"},
  {"p": "assets/fish/beluga.png", "s": 97999, "t": "fish"},
  {"p": "assets/fish/ersh.png", "s": 156244, "t": "fish"},
  {"p": "assets/fish/forel.png", "s": 132399, "t": "fish"},
  {"p": "assets/fish/golavl.png", "s": 145886, "t": "fish"},
  {"p": "assets/fish/gustera.png", "s": 219058, "t": "fish"},
  {"p": "assets/fish/harius.png", "s": 157649, "t": "fish"},
  {"p": "assets/fish/karas.png", "s": 236380, "t": "fish"},
  {"p": "assets/fish/karp.png", "s": 165978, "t": "fish"},
  {"p": "assets/fish/krasnoperka.png", "s": 152496, "t": "fish"},
  {"p": "assets/fish/lenok.png", "s": 118475, "t": "fish"},
  {"p": "assets/fish/leshch.png", "s": 233314, "t": "fish"},
  {"p": "assets/fish/lin.png", "s": 121779, "t": "fish"},
  {"p": "assets/fish/losos.png", "s": 125178, "t": "fish"},
  {"p": "assets/fish/nalim.png", "s": 87593, "t": "fish"},
  {"p": "assets/fish/okun.png", "s": 174206, "t": "fish"},
  {"p": "assets/fish/palia.png", "s": 113721, "t": "fish"},
  {"p": "assets/fish/peskar.png", "s": 102103, "t": "fish"},
  {"p": "assets/fish/plotva.png", "s": 144752, "t": "fish"},
  {"p": "assets/fish/raduzhka.png", "s": 129523, "t": "fish"},
  {"p": "assets/fish/rotan.png", "s": 143667, "t": "fish"},
  {"p": "assets/fish/ryapushka.png", "s": 99155, "t": "fish"},
  {"p": "assets/fish/sazan.png", "s": 160972, "t": "fish"},
  {"p": "assets/fish/serkaras.png", "s": 218169, "t": "fish"},
  {"p": "assets/fish/shchuka.png", "s": 108621, "t": "fish"},
  {"p": "assets/fish/sig.png", "s": 125030, "t": "fish"},
  {"p": "assets/fish/som.png", "s": 83989, "t": "fish"},
  {"p": "assets/fish/sterlyad.png", "s": 67037, "t": "fish"},
  {"p": "assets/fish/sudak.png", "s": 117917, "t": "fish"},
  {"p": "assets/fish/taimen.png", "s": 115817, "t": "fish"},
  {"p": "assets/fish/uklejka.png", "s": 97603, "t": "fish"},
  {"p": "assets/fish/vyun.png", "s": 50204, "t": "fish"},
  {"p": "assets/fish/yaz.png", "s": 145388, "t": "fish"},
  {"p": "assets/fish/zherekh.png", "s": 113931, "t": "fish"},
  {"p": "assets/fish/zolotaya.png", "s": 258363, "t": "fish"},
  {"p": "assets/bg/lake_day.jpg", "s": 401747, "t": "img"},
  {"p": "assets/bg/lake_evening.jpg", "s": 409901, "t": "img"},
  {"p": "assets/bg/lake_night.jpg", "s": 368751, "t": "img"},
  {"p": "assets/bg/mountain_day.jpg", "s": 409689, "t": "img"},
  {"p": "assets/bg/mountain_evening.jpg", "s": 399036, "t": "img"},
  {"p": "assets/bg/mountain_night.jpg", "s": 356138, "t": "img"},
  {"p": "assets/bg/north_day.jpg", "s": 367352, "t": "img"},
  {"p": "assets/bg/north_evening.jpg", "s": 390713, "t": "img"},
  {"p": "assets/bg/north_night.jpg", "s": 400502, "t": "img"},
  {"p": "assets/bg/pond_day.jpg", "s": 364535, "t": "img"},
  {"p": "assets/bg/pond_evening.jpg", "s": 379829, "t": "img"},
  {"p": "assets/bg/pond_night.jpg", "s": 362423, "t": "img"},
  {"p": "assets/bg/river_day.jpg", "s": 379666, "t": "img"},
  {"p": "assets/bg/river_evening.jpg", "s": 402782, "t": "img"},
  {"p": "assets/bg/river_night.jpg", "s": 364406, "t": "img"},
  {"p": "assets/bg/swamp_day.jpg", "s": 374392, "t": "img"},
  {"p": "assets/bg/swamp_evening.jpg", "s": 393943, "t": "img"},
  {"p": "assets/bg/swamp_night.jpg", "s": 360063, "t": "img"},
  {"p": "assets/bg/volga_day.jpg", "s": 337145, "t": "img"},
  {"p": "assets/bg/volga_evening.jpg", "s": 358204, "t": "img"},
  {"p": "assets/bg/volga_night.jpg", "s": 354802, "t": "img"},
  {"p": "assets/music/menu.mp3", "s": 3001514, "t": "media"},
  {"p": "assets/amb/birds.mp3", "s": 840821, "t": "media"},
  {"p": "assets/amb/night.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/north.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/rain.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/rapids.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/river.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/swamp.mp3", "s": 813027, "t": "media"},
  {"p": "assets/amb/wind.mp3", "s": 813027, "t": "media"},
  {"p": "assets/sfx/bell.mp3", "s": 15091, "t": "sfx", "name": "bell"},
  {"p": "assets/sfx/bubbles.mp3", "s": 12897, "t": "sfx", "name": "bubbles"},
  {"p": "assets/sfx/buy.mp3", "s": 9135, "t": "sfx", "name": "buy"},
  {"p": "assets/sfx/cast.mp3", "s": 9135, "t": "sfx", "name": "cast"},
  {"p": "assets/sfx/click.mp3", "s": 1925, "t": "sfx", "name": "click"},
  {"p": "assets/sfx/coin.mp3", "s": 10389, "t": "sfx", "name": "coin"},
  {"p": "assets/sfx/drag.mp3", "s": 12897, "t": "sfx", "name": "drag"},
  {"p": "assets/sfx/error.mp3", "s": 5060, "t": "sfx", "name": "error"},
  {"p": "assets/sfx/flop.mp3", "s": 15091, "t": "sfx", "name": "flop"},
  {"p": "assets/sfx/hookset.mp3", "s": 5687, "t": "sfx", "name": "hookset"},
  {"p": "assets/sfx/j_catch.mp3", "s": 51453, "t": "sfx", "name": "j_catch"},
  {"p": "assets/sfx/j_fail.mp3", "s": 62319, "t": "sfx", "name": "j_fail"},
  {"p": "assets/sfx/j_legend.mp3", "s": 68171, "t": "sfx", "name": "j_legend"},
  {"p": "assets/sfx/j_levelup.mp3", "s": 48945, "t": "sfx", "name": "j_levelup"},
  {"p": "assets/sfx/j_quest.mp3", "s": 50199, "t": "sfx", "name": "j_quest"},
  {"p": "assets/sfx/j_sell.mp3", "s": 41839, "t": "sfx", "name": "j_sell"},
  {"p": "assets/sfx/j_trophy.mp3", "s": 76112, "t": "sfx", "name": "j_trophy"},
  {"p": "assets/sfx/j_unlock.mp3", "s": 55214, "t": "sfx", "name": "j_unlock"},
  {"p": "assets/sfx/nibble.mp3", "s": 3806, "t": "sfx", "name": "nibble"},
  {"p": "assets/sfx/paper.mp3", "s": 5060, "t": "sfx", "name": "paper"},
  {"p": "assets/sfx/plop.mp3", "s": 6314, "t": "sfx", "name": "plop"},
  {"p": "assets/sfx/reel.mp3", "s": 12897, "t": "sfx", "name": "reel"},
  {"p": "assets/sfx/snag.mp3", "s": 10389, "t": "sfx", "name": "snag"},
  {"p": "assets/sfx/snap.mp3", "s": 11643, "t": "sfx", "name": "snap"},
  {"p": "assets/sfx/splash_b.mp3", "s": 17599, "t": "sfx", "name": "splash_b"},
  {"p": "assets/sfx/splash_s.mp3", "s": 7881, "t": "sfx", "name": "splash_s"},
];
